title: Danel's blog
author: Danel Adra
email: adradanel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Siia hakkan postitama oma päevastest tegevustest ja mõtetest.
theme: jekyll-theme-minimal
 

# social links
twitter_username: danel1994
github_username:  adradanel

show_excerpts: true # set to false to remove excerpts on the homepage
